# Generated by Django 6.0.6 on 2026-06-26 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountmanager', '0002_studentprofile_klass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField()),
                ('Grade', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.studentprofile')),
                ('Subjectid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Studentapp.subject')),
            ],
        ),
    ]
