# Generated by Django 6.0.6 on 2026-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='Month',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
