# Generated by Django 6.0.6 on 2026-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0002_alter_grades_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='Month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1),
        ),
    ]
