# Generated by Django 6.0.6 on 2026-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0003_alter_grades_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='Month',
            field=models.CharField(choices=[('الاول', 'frist'), ('الثاني ', 'secound'), ('الثالث', 'threrd')], max_length=10),
        ),
    ]
