# Generated by Django 6.0.6 on 2026-06-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0005_grades_evaluation'),
        ('accountmanager', '0002_studentprofile_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.studentprofile'),
        ),
    ]
