# Generated by Django 6.0.6 on 2026-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0006_alter_grades_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='Month',
            field=models.CharField(choices=[('1', 'frist'), ('2', 'secound'), ('3', 'threrd')], max_length=10),
        ),
    ]
