# Generated by Django 6.0.6 on 2026-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='klass',
            field=models.CharField(default=1.0, max_length=3),
            preserve_default=False,
        ),
    ]
