# Generated by Django 6.0.6 on 2026-06-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0002_studentprofile_klass'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='career',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
