# Generated by Django 6.0.6 on 2026-06-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0003_teacherprofile_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='career',
            field=models.CharField(max_length=20),
        ),
    ]
