# Generated by Django 6.0.6 on 2026-06-30 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0004_alter_teacherprofile_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_year', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='School_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='Academic_year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='AcademicYear',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.academic_year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='klass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.school_classes'),
        ),
    ]
