# Generated by Django 6.0.6 on 2026-06-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountmanager', '0004_alter_teacherprofile_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(verbose_name=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weeklyschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.ManyToManyField(to='accountmanager.teacherprofile')),
                ('day', models.ManyToManyField(to='Teacherapp.week')),
            ],
        ),
    ]
