# Generated by Django 6.0.6 on 2026-06-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0001_initial'),
        ('accountmanager', '0005_academic_year_school_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='Academicyear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.academic_year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.school_classes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='week',
            name='day_name',
            field=models.CharField(),
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='Teacher_name',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherapp.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='Teacher_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accountmanager.teacherprofile'),
            preserve_default=False,
        ),
    ]
