# Generated by Django 6.0.6 on 2026-07-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherapp', '0002_session_weeklyschedule_academicyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='day',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherapp.week'),
            preserve_default=False,
        ),
    ]
